# Generated by Django 5.1.1 on 2024-11-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='desc',
            new_name='description',
        ),
    ]
