# Generated by Django 5.1.1 on 2024-11-11 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Options',
            new_name='Choices',
        ),
        migrations.RenameField(
            model_name='choices',
            old_name='is_answer',
            new_name='is_correct',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='title',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='score',
        ),
        migrations.AddField(
            model_name='questions',
            name='score',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='questions',
            name='no',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
